# Generated by Django 4.1.2 on 2022-10-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Motorcicle name')),
                ('image', models.ImageField(upload_to='media', verbose_name='ImageField')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('characteristics', models.TextField(max_length=10000, verbose_name='characteristics')),
            ],
            options={
                'verbose_name': 'Motorcicle',
                'verbose_name_plural': 'Motorcicles',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
